### ISSUE TITLE
Verification for FTP functions/commands

### ISSUE THREAD

**Issue by ABKingbird** [ldab/ESP32_FTPClient#11]
Hello.
First of all I want to state that this is not an issue, I just didn't know where else to post that question.
Also, I want to thank you for this library, it helped me in a state of emergency :P

Is there any way to verify that a certain action (for example: ftp.Write(...) ) was done successfully?
There is already a function called ftp.isConnected() that returns a boolean but what if I want to do multiple actions during a connection and some of them just don't happen from the server's side.

I understand that the function GetFTPAnswer is used for debugging/verification but I cant implement a proper condition since every other functions returns void.

Thank you in advance.

**Comment by ldab** [comment]
Yes, here is where you would pick the command response https://github.com/ldab/ESP32_FTPClient/blob/8bba164143fb00f0bacfd93d0b143015775a2b7b/src/ESP32_FTPClient.cpp#L78

And here is the list of command responses https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes

You can modify the function or create another variable accordingly to your needs.
