### ISSUE TITLE
Trying to upload a picture, ESP32 Cam -> local ftp server

### ISSUE THREAD

**Issue by alexw22** [ldab/ESP32_FTPClient#19]
Hello there I am trying to upload a picture from the ESP32 Cam module to a local ftp server I have running. I managed to get the example upload sketch working and successfully uploaded the octocat.jpg picture so things on the ftp/credential side seem to be fine.

EDIT: I also managed to get the proper filenames over and the files with correct filenames are being generated however they are empty or very small.

I am suspecting things are breaking in these lines as I was getting multiple compile errors until it compiled but unfortunately noticed a Guru Meditation Error and a memory dump following it:

**This is how the picture is taken:**
// Take Picture with Camera
  fb = esp_camera_fb_get();  
  if(!fb) {
    Serial.println("Camera capture failed");
    return;
  }

 File file = fs.open(path.c_str(), FILE_WRITE);
  if(!file){
    Serial.println("Failed to open file in writing mode");
  }
  else {
    file.write(fb->buf, fb->len); // payload (image), payload length
    Serial.printf("Saved file to path: %s\n", path.c_str());
    EEPROM.write(0, pictureNumber);
    EEPROM.commit();
  }
  file.close();

**This is how I am trying to send it and Im expecting the problem to be hidden here:**
// Create the new file and send the image
  ftp.InitFile("Type I");
  ftp.NewFile(path.c_str());
  ftp.WriteData( fb->buf, sizeof(fb->len) );          //<- **expecting a problem here**
  ftp.CloseFile();

In general I am trying to combine [this sketch](https://randomnerdtutorials.com/esp32-cam-pir-motion-detector-photo-capture/) and implement ftp functionality so that a copy of each file is sent to an ftp server.

Any help on this is appreciated as I am quite lost at the moment

**Comment by ldab** [comment]
Please share you full code.

Start the library with verbose mode "2" and share the serial monitor.

Since the example provided with the library works, it's likely that your code break due to the use of SD card or the EEPROM
