### ISSUE TITLE
Ftp Client from Ethernet connections

### ISSUE THREAD

**Issue by umbertoge** [ldab/ESP32_FTPClient#22]
Hi
good work for wifi client,
but can you help me for set library for use it for ethernet connection to ftp server?
Thanks
Umberto

**Comment by ldab** [comment]
https://playground.arduino.cc/Code/FTP/

**Comment by umbertoge** [comment]
Thanks. It use also with esp32 board?
Is compatible with lan8720?
Very thanks
Umberto
