### ISSUE TITLE
ContentList(const char * dir, String * list); causes the download of the entire file

### ISSUE THREAD

**Issue by pcbtborges** [ldab/ESP32_FTPClient#23]
I am looking to confirm if the upload of a file have completed successfully and for that, after uploading the file I used the command below expecting a list of all files in the indicated directory (dir) but it takes a long time and brings the entire content of the directory and files.
My objective is to compare if the name and size of the file I transferred matches any file on the list so I can proceed and delete the file from local SPIFFS partition.

My command (taken from one of the examples) goes like this:
const char * dir = "/"   and 
String       list[128];

ContentList(const char * dir, String * list);

**Comment by ldab** [comment]
This is not an issue with the library, closing

**Comment by pcbtborges** [comment]
Do You mean it is a problem with the FTP Server?
In case it is, is there a way to select a FTP server that works with the library?
Thanks

**Comment by ldab** [comment]
No, what I meant is that what you wrote describes a misuse or misunderstanding of the commands, and not an issue.

**Comment by pcbtborges** [comment]
OK, sorry, I tried to find some documentation but failed. Can you provide some source where I can learn the proper use for the methods provided by the library?
Thanks

**Comment by ldab** [comment]
https://en.wikipedia.org/wiki/List_of_FTP_commands
