### ISSUE TITLE
how to read sd card and transfer to FTP?

### ISSUE THREAD

**Issue by georgeyjr** [ldab/ESP32_FTPClient#24]
hello. first, nice work, congratz. already tested this project and its worked for me =)
would you mind to write a code to read a txt file from an sd card and transfer to ftp? i can't find anywhere and i'm a beginner.
i'm wondering how can i write correctly in the  ftp.writedata area.
thanks

**Comment by ldab** [comment]
Unfortunately I'll not be able to help
