### ISSUE TITLE
Sending CSV files From SD card to FTP Server

### ISSUE THREAD

**Issue by KvarTechnologies** [ldab/ESP32_FTPClient#31]
My csv File which is present in SD card, is not send appropriately to the ftp File Server. The code is below

void Send_FTP_file(fs::FS& fs, const char* path, ESP32_FTPClient ftpClient) {
    //Serial.printf("Reading file: %s\n", path);

    String fullPath = "/";
    fullPath.concat(path);
    File file = SD.open(fullPath);
    if(!file){
        Serial.print("Failed to open file for reading");
        return;
    }
    
    ftpClient.InitFile("Type I");
    ftpClient.NewFile(path);
    //ftpClient.WriteData( file, sizeof(file) );
    
    while (file.available()) {
        // Create and fill a buffer
        unsigned char buf[1024];
        int readVal = file.read(buf, sizeof(buf));
        ftpClient.WriteData(buf,sizeof(buf));
    }*
    ftpClient.CloseFile();
    file.close();

}

**Comment by ldab** [comment]
Can you please elaborate "is not send appropriately" ? Do you receive just part of it?

What is the terminal output when you use `ESP32_FTPClient ftp (ftp_server,ftp_user,ftp_pass, 5000, 2);` for extra prints on the library?
