### ISSUE TITLE
Sending File format to ftp

### ISSUE THREAD

**Issue by KvarTechnologies** [ldab/ESP32_FTPClient#33]
I have been trying to read the sd card file and then write it to the ftp server , which causes 2 major issues
1. The file is large which causes it to use all the string allocated memory, and then only been able to send only limited data. Is there any way to Send the File to FTP using File format?
2. File needs to written byte by byte , any faster way to do it?

**Comment by ldab** [comment]
1. You will probably run out of memory and for that reason will need to send in parts;
2. Not that I'm aware of.

**Comment by KvarTechnologies** [comment]
Size of my csv file is 90816 in int.  Is there any fastest way to upload the file
