### ISSUE TITLE
FTP Offline

### ISSUE THREAD

**Issue by KvarTechnologies** [ldab/ESP32_FTPClient#35]
code:-
ESP32_FTPClient ftp1 (ftp_server_t,ftp_user_t,ftp_pass_t,3000,2);

void ftp_send(){
  int chn;
  if(FTP_enable){
    if(ftp_enable1==1){
      ftp1.OpenConnection();
      if(ftp1.isConnected()){
        Serial.println("FTP 1 : Connected");
        ftp1.ChangeWorkDir(ftp_dir[0]);
        for(chn=0;chn<sensors;chn++)
        {
        if(enchn[chn]!=0){
          char fname[30];
          char dem[30];
          //String temp ="20230324_KVARtest1.csv";
          sprintf(fname,"%04d%02d%02d_%s.csv",curdate.year+2000,curdate.mon,curdate.date,compid[chn].c_str());
          //sprintf(fname,"%s",temp);
          Send_FTP_file(SD, fname, ftp1);                 // 272,546
          sprintf(dem,"File Send: %s",fname);
          Serial.println(dem);
        }
        }
      }else{
        Serial.println("FTP 1 : DISCONNECTED");
      }
      ftp1.CloseConnection();
  
    }
}

void Send_FTP_file(fs::FS& fs, const char* path, ESP32_FTPClient ftpClient) {
    //Serial.printf("Reading file: %s\n", path);

    String fullPath = "/";
    fullPath.concat(path);
    Serial.print("File Path:");
    Serial.print(path);
    File file = SD.open(fullPath);
    if(!file){
        Serial.print("Failed to open file for reading");
        return;
    }
    
    ftpClient.InitFile("Type I");
    ftpClient.NewFile(path);
    char sz = file.size();
    int fileSize = file.size();
    Serial.print("File Size:");
    Serial.print(fileSize);   
    unsigned char * downloaded_file = (unsigned char *) malloc(fileSize);    
    size_t bytesRead = file.read(downloaded_file, fileSize); // read the file contents into the array   
    //const char* myString = reinterpret_cast<const char*>(downloaded_file);  // for converting unsigned char to const char*
    ftpClient.WriteData(downloaded_file, fileSize);   
    free(downloaded_file);
    ftpClient.CloseFile();
    file.close();

    
}

Error:
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
Send USER<CR><LF>
Send PASSWORD<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>
FTP error: Offline<LF>
Connecting to: 13.126.134.217<CR><LF>
Command connected<CR><LF>....

It remains in the condition unitl  FTP connected, Can u impalement no of tries in the FTPAnswer routine. To skip if tit exceeds no of tries . So that it can again try to reconnect when the function of send is called. Or is there any other way to tackle this issue

**Comment by ldab** [comment]
I’ll not work on that, feel free to change as per your requirements.

**Comment by KvarTechnologies** [comment]
i am unable to figureout the exact issue with ftp : offline, it shows ftp offline and after few tries it connects. Again after few time , shows FTP : OFFLINE
