### ISSUE TITLE
Esp32 resets wen data is sennding

### ISSUE THREAD

**Issue by GirishPawar1999** [ldab/ESP32_FTPClient#39]
The log of the file is given below, the reset happens frequently . I have cross checked the user name, passwords host served details : 
''' 
Send TYPE<CR><LF>
Type I<CR><LF>
Send PASV<CR><LF>
Data port: 65218<CR><LF>
Data connection established<CR><LF>
Send STOR<CR><LF>
File Size:414761Writing<CR><LF>
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.<CR><LF>
<CR><LF>
Core  0 register dump:<CR><LF>
PC      : 0x400f42d7  PS      : 0x00060730  A0      : 0x800f4338  A1      : 0x3ffdf050  <CR><LF>
A2      : 0x3ffdf108  A3      : 0x3ffdf1b8  A4      : 0x00000000  A5      : 0x00065429  <CR><LF>
A6      : 0x00000000  A7      : 0x000000ef  A8      : 0x00000000  A9      : 0x00000000  <CR><LF>
A10     : 0x00000001  A11     : 0x00000001  A12     : 0x00065429  A13     : 0x3ffb6954  <CR><LF>
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x0000000f  EXCCAUSE: 0x0000001c  <CR><LF>
EXCVADDR: 0x00000000  LBEG    : 0x4008ac25  LEND    : 0x4008ac35  LCOUNT  : 0xfffffffe  <CR><LF>
<CR><LF>
<CR><LF>
Backtrace: 0x400f42d4:0x3ffdf050 0x400f4335:0x3ffdf070 0x400e91cf:0x3ffdf090 0x400e96f2:0x3ffdf0e0<CR><LF>
<CR><LF>
<CR><LF>
<CR><LF>
<CR><LF>
ELF file SHA256: 153cbdbb158e7ded<CR><LF>
<CR><LF>
E (16979) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0<CR><LF>
Rebooting...<CR><LF>
ÓRöîfgRâ
'''

**Comment by ldab** [comment]
`LoadProhibited` indicates you tried to load a variable form an illegal address. Please read the ESP32 [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#loadprohibited-storeprohibited)

You will find that "EXCVADDR register in the register dump. If this address is **zero**, it usually means that the application has attempted to dereference a **NULL pointer**."

This is not a library issue, thus closing it.
