### ISSUE TITLE
Parametric management of FTP parameters

### ISSUE THREAD

**Issue by biggiu** [ldab/ESP32_FTPClient#40]
Hello and congratulations for the good work done.
I tried the library and everything works great.
Now however, I would like to make the access parameters to the FTP area parametric.
I planned to read these parameters from SD-CARD and assign them to the variables:

char ftp_server[] = "";
char ftp_user[] = "";
char ftp_pass[] = "";

for example :

String FTP_SER;
String FTP_USR;
String FTP_PWD;

these variables are read from SD-CARD.

Then I try to do:
char ftp_server[] = FTP_SER;
char ftp_user[] = FTP_USR;
char ftp_pass[] = FTP_PWD;

but I can't get it to work no matter what I try.
It's true that I'm not very good with the Arduino language but it seems strange to me not to be able to manage something apparently so simple.

Would you be so kind as to give me a hand.
Thank you for any collaboration.

**Comment by ldab** [comment]
You can't direct assign a `String` to a char array. I believe you need https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/tochararray/

**Comment by biggiu** [comment]
Hi and sorry if I keep bothering you. I followed your advice and tried the following code:

#include "Arduino.h"
#include <WiFi.h>
#include <WiFiClient.h> 
#include <ESP32_FTPClient.h>
#include "octocat.h"

#define WIFI_SSID ""
#define WIFI_PASS ""

  String FTP_SER;
  String FTP_USR;
  String FTP_PWD;
  String w0;
  char ftp_server[] = "";
  char ftp_user[] = "";
  char ftp_pass[] = "";

  int LW = 0;

  void setup()
  {
    
    Serial.begin(115200);
    delay(100);
        
    FTP_SER = "";
    FTP_USR = "";
    FTP_PWD = "";

    
    LW = FTP_SER.length()+1;
    FTP_SER.toCharArray(ftp_server,LW);
    Serial.printf("ftp_server = %s\n",ftp_server);
    
    LW = FTP_USR.length()+1;
    FTP_USR.toCharArray(ftp_user,LW);
    Serial.printf("ftp_user = %s\n",ftp_user);
    
    LW = FTP_PWD.length()+1;
    FTP_PWD.toCharArray(ftp_pass,LW);
    Serial.printf("ftp_pass = %s\n",ftp_pass);

    ConWiFi();

    ChkConFtp();
  }

    /************************************************/
    /* GESTIONE CONNESSIONE A WiFi                  */
    /************************************************/
    void ConWiFi()
    {
      WiFi.begin( WIFI_SSID, WIFI_PASS );
  
      Serial.println("Connecting Wifi...");
      while (WiFi.status() != WL_CONNECTED)
      {
        delay(500);
        Serial.print(".");
      }
      Serial.println("");
      Serial.print("IP address: ");
      Serial.println(WiFi.localIP());
    }

    /************************************************/
    /* GESTIONE CONNESSIONE A FTP                   */
    /************************************************/
    void ChkConFtp()
    {

      ESP32_FTPClient ftp (ftp_server,ftp_user,ftp_pass, 5000, 2);
     
      ftp.OpenConnection();
      if ( ftp.isConnected() )
      {
        Serial.println("Mi sono connesso all'area FTP ");
       
        ftp.ChangeWorkDir( "/httpdocs/download/" );
        // Scrittura Messaggio                
        //ftp.DeleteFile(PRO_OPE);        
        ftp.InitFile("Type A");
        ftp.NewFile("prova.txt");
        ftp.Write("Ho scritto ti amo sulla sabbia");
        ftp.CloseFile();
        ftp.CloseConnection(); 
      }
      else
        Serial.println("Impossibile accedere all'area FTP ");
    }

  void loop()
  {

  }

The result I obtain is decidedly astonishing because the software indicates as connection:
Connecting to: (ftp_password)
indicate the password instead of the server.

If you have any advice to give me I would be extremely grateful.
Good work

**Comment by ldab** [comment]
On the code shared I do not see where it would print “ Connecting to:”

It is recommended to paste the full output of the terminal.

this is not related to this library so I’d suggest you post your question on arduino forum.

without spending more time on it, it seems like your char ftp_server etc is not big enough to contain the string.

**Comment by biggiu** [comment]
Hello and thanks for the prompt response. I'll try to explain the problem differently:

I define the char variables:

   char ftp_server[] = "";
   char ftp_user[] = "";
   char ftp_pass[] = "";

I associate the values with String variables:

FTP_SER = "ftpserver";
FTP_USR = "ftpuser";
FTP_PWD = "ftppassword";

after using toCharArray I get:

ftp_server = ftpserver;
ftp_user = ftpuser;
ftp_pass = ftppassword

So far everything is fine and nothing strange.
Now, as soon as I start the function:

ESP32_FTPClient ftp (ftp_server,ftp_user,ftp_pass, 5000, 2);

The following message appears on the Arduino IDE serial monitor:

Connecting to: passwordftp

I put dummy values as FTP parameters so as not to display the real ones, but the result doesn't change.
The strange thing, which I don't think depends on Arduino, is this exchange of parameters. Which doesn't happen using your example.
If you spend some time testing the code you might find something that wasn't expected.

Thanks anyway for your great work.
Greetings.

**Comment by ldab** [comment]
As I wrote earlier, you’re declaring the variables wrong.

try

char ftp_pass[64]…. Etc

**Comment by biggiu** [comment]
Thanks for your patience, everything works perfectly now.
Good work
