### ISSUE TITLE
Wifi by smartphone HotSpot

### ISSUE THREAD

**Issue by biggiu** [ldab/ESP32_FTPClient#41]
Hello and sorry if I bother you.
I used this splendid library for a project related to the ESP32CAM board.
The purpose is to read some parameters, via Wifi, from Firebase to parameterize the photo shot, take the shot and save it in an FTP area.
Working with a home WiFi, everything works perfectly.
Using a phone's HotSpot, the firebase connection part works while the application cannot handle the FTP connection.
I use the connection where the port is automatically set to 21.
Do you have any suggestions?
Best regards

**Comment by ldab** [comment]
There were several similar issues like that mentioned here earlier, for example https://github.com/ldab/ESP32_FTPClient/issues/21#issuecomment-761692679

my suggestion would be to change the port or try from your computer while connected to the hotspot just to confirm that the behaviour is similar
