### ISSUE TITLE
Capture error

### ISSUE THREAD

**Issue by biggiu** [ldab/ESP32_FTPClient#48]
HI,
I'm using this library extensively and I find it really well done. Compliments.
I just have one doubt, which I hope you can resolve.
There is the possibility of catching any errors, such as:
1) failure to connect
2) Error downloading a txt file

and in general identify errors that may occur during use of the library?

Thanks for the kind cooperation.

**Comment by ldab** [comment]
The functions are all void, but by passing 2 as debug as here https://github.com/ldab/ESP32_FTPClient/blob/e5f89d4aa36c2a745ccf3d8d27bcad17410cb9af/examples/upload_image/upload_image.ino#L25

you should see extra prints.
