### ISSUE TITLE
Not able to log in or upload a file to an FTP server hosted by Node

### ISSUE THREAD

**Issue by zelms** [ldab/ESP32_FTPClient#49]
## What is the issue  
The library fails to log in to an FTP server created using Node and Ftp-srv version 4.6.3 hosted on Ubuntu 23.10. Additionally, after the log in issue is resolved, the ftp server throws an "illegal operation on a directory" error when a file upload attempt is made. 

## What have I done to resolve it  
I found that sending some commands as one string, instead of two separate strings, seemed to fix the issue. I believe the FTP server was getting confused with commands getting sent as multiple strings. This solution will be made clearer in a pull request.

**Comment by ldab** [comment]
we shall continue the conversation on the PR then.
